version: '2'
services:
  wmte-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/wmte/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wmte
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
